# https://stackoverflow.com/a/59399062/3343716
name: Node CI

on:
  push:

  # https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule
  # Scheduled workflows run on the latest commit on the default or base branch.
  # * is a special character in YAML so you have to quote this string
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          yarn install
      - name: Run tests
        run: |
          yarn test
